# Generated by Django 5.1.1 on 2024-09-23 06:46

import nextfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField(verbose_name='Message body')),
                ('sender_ip', models.GenericIPAddressField()),
                ('mail_sent', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=nextfolio.models.Resume.filepath, verbose_name='Resume File')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
