# Generated by Django 5.1.1 on 2024-10-01 17:17

import nextfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextfolio', '0002_rename_sender_email_message_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(db_index=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('country_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=nextfolio.models.Resume.filepath, validators=[nextfolio.models.pdf_validator], verbose_name='Resume File'),
        ),
    ]
